In [2]:
import pandas as pd

# 创建数据
data = {
    "Year": [],
    "Month": [],
    "Rent_Hong_Kong": [],
    "Rent_Kowloon": [],
    "Rent_New_Territories": [],
    "Price_Hong_Kong": [],
    "Price_Kowloon": [],
    "Price_New_Territories": []
}

# 填充数据（从 1999 年 1 月到 2025 年 1 月）
for year in range(1999, 2026):
    months = 12 if year < 2025 else 1  # 2025 年只到 1 月
    for month in range(1, months + 1):
        data["Year"].append(year)
        data["Month"].append(month)

# 从表格中提取数据
# 由于数据量较大，这里手动输入所有数据
data["Rent_Hong_Kong"] = [
    # 1999
    776, 793, 790, 759, 717, 847, 831, 704, 821, 686, 835, 729,
    # 2000
    767, 803, 803, 761, 762, 896, 787, 789, 836, 779, 808, 793,
    # 2001
    775, 882, 898, 787, 800, 869, 796, 798, 917, 901, 1066, 796,
    # 2002
    780, 764, 852, 743, 920, 798, 750, 725, 762, 757, 834, 790,
    # 2003
    710, 796, 936, 680, 705, 769, 654, 656, 806, 748, 850, 745,
    # 2004
    703, 893, 821, 689, 944, 933, 907, 820, 862, 833, 900, 844,
    # 2005
    804, 744, 988, 834, 1079, 933, 969, 898, 961, 919, 1126, 941,
    # 2006
    812, 888, 1005, 973, 1034, 951, 1037, 960, 1146, 941, 1151, 1019,
    # 2007
    1000, 887, 1108, 935, 1032, 1146, 1040, 1136, 1132, 1077, 1225, 942,
    # 2008
    1088, 1137, 1274, 1033, 1183, 1153, 1568, 1190, 1224, 1122, 1143, 1050,
    # 2009
    858, 972, 1044, 955, 1068, 1087, 1180, 1150, 1135, 1168, 1212, 1056,
    # 2010
    1015, 985, 1395, 1027, 1266, 1332, 1440, 1262, 1339, 1225, 1187, 1277,
    # 2011
    1039, 1245, 1230, 1192, 1384, 1450, 1311, 1439, 1306, 1280, 1389, 1295,
    # 2012
    1137, 1245, 1555, 1353, 1456, 1489, 1603, 1407, 1733, 1487, 1633, 1450,
    # 2013
    1297, 1288, 1754, 1393, 1639, 1604, 1616, 1546, 1618, 1368, 1759, 1501,
    # 2014
    1232, 1559, 1725, 1648, 1574, 1887, 1699, 1551, 1818, 1546, 1456, 1669,
    # 2015
    1453, 1355, 1560, 1683, 1518, 1796, 1580, 1781, 1579, 1618, 1736, 1514,
    # 2016
    1516, 1464, 1701, 1518, 1474, 1432, 1714, 1402, 1446, 1414, 1453, 1381,
    # 2017
    1463, 1476, 1599, 1620, 1426, 1584, 1472, 1572, 1398, 1470, 1591, 1478,
    # 2018
    1427, 1461, 1551, 1411, 1529, 1574, 1520, 1692, 1682, 1535, 1602, 1383,
    # 2019
    1357, 1504, 1690, 1750, 1531, 1736, 1511, 1537, 1438, 1391, 1421, 1221,
    # 2020
    1182, 1280, 1322, 1144, 1036, 1249, 1173, 1137, 1318, 1149, 1264, 1253,
    # 2021
    1219, 1135, 1340, 1272, 1194, 1358, 1208, 1282, 1339, 1131, 1341, 1270,
    # 2022
    1199, 1278, 1278, 1066, 1219, 1244, 1249, 1212, 1253, 1067, 1265, 1042,
    # 2023
    1031, 1454, 1307, 1296, 1216, 1437, 1257, 1309, 1334, 1174, 1236, 1204,
    # 2024
    1116, 1100, 1141, 1201, 1099, 1169, 1215, 1200, 1303, 1116, 1106, 1066,
    # 2025
    967
]

data["Rent_Kowloon"] = [
    # 1999
    799, 835, 865, 831, 861, 838, 961, 930, 914, 814, 917, 1101,
    # 2000
    813, 1056, 1015, 920, 991, 889, 1066, 950, 909, 955, 1118, 1005,
    # 2001
    889, 1010, 921, 890, 858, 905, 869, 898, 915, 916, 983, 1218,
    # 2002
    772, 829, 950, 853, 890, 815, 889, 789, 765, 872, 928, 1050,
    # 2003
    776, 849, 852, 739, 699, 801, 794, 751, 804, 837, 915, 1216,
    # 2004
    807, 838, 888, 798, 908, 896, 1017, 799, 871, 986, 954, 1053,
    # 2005
    854, 829, 1005, 892, 838, 896, 942, 1138, 946, 993, 996, 1398,
    # 2006
    1138, 914, 1030, 875, 883, 908, 1143, 884, 1057, 1055, 1111, 1065,
    # 2007
    857, 917, 935, 944, 943, 947, 970, 1128, 1094, 1105, 1196, 1316,
    # 2008
    952, 1004, 1169, 998, 1047, 1200, 1180, 1067, 1145, 1096, 1276, 1200,
    # 2009
    965, 930, 1162, 938, 973, 1007, 987, 1097, 1145, 1154, 1321, 1230,
    # 2010
    972, 1001, 1222, 1049, 1097, 1202, 1194, 1137, 1320, 1230, 1341, 1301,
    # 2011
    996, 1036, 1262, 1057, 1236, 1249, 1277, 1343, 1417, 1242, 1465, 1361,
    # 2012
    1235, 1261, 1455, 1296, 1346, 1690, 1389, 1339, 1589, 1524, 1646, 1539,
    # 2013
    1334, 1206, 1547, 1373, 1385, 1416, 1555, 1631, 1695, 1400, 1705, 1343,
    # 2014
    1401, 1360, 1629, 1441, 1430, 1548, 1452, 1463, 1665, 1643, 1827, 1537,
    # 2015
    1497, 1520, 1774, 1518, 1575, 1530, 1498, 1527, 1515, 1367, 1350, 1424,
    # 2016
    1174, 1286, 1448, 1332, 1333, 1289, 1186, 1296, 1547, 1307, 1576, 1233,
    # 2017
    1282, 1330, 1455, 1264, 1450, 1290, 1271, 1382, 1624, 1445, 1561, 1403,
    # 2018
    1328, 1412, 1578, 1481, 1373, 1394, 1301, 1398, 1597, 1499, 1369, 1354,
    # 2019
    1345, 1304, 1591, 1380, 1397, 1362, 1340, 1453, 1448, 1418, 1297, 1318,
    # 2020
    1210, 1169, 1129, 1085, 1176, 1124, 1117, 1069, 1121, 1053, 1160, 1157,
    # 2021
    1033, 1192, 1152, 1096, 1098, 1101, 1030, 1200, 1123, 1103, 1224, 1103,
    # 2022
    1088, 1070, 1115, 1116, 1051, 1126, 1049, 1099, 1110, 1078, 1232, 1114,
    # 2023
    978, 1125, 1187, 1184, 1199, 1170, 1151, 1164, 1208, 1143, 1287, 1210,
    # 2024
    1069, 1104, 1134, 1038, 1023, 1123, 1066, 1045, 1061, 1222, 1438, 1068,
    # 2025
    975
]

data["Rent_New_Territories"] = [
    # 1999
    551, 568, 679, 681, 617, 704, 650, 679, 679, 784, 683, 754,
    # 2000
    622, 619, 771, 679, 739, 787, 697, 760, 807, 768, 883, 789,
    # 2001
    653, 635, 713, 675, 730, 705, 725, 725, 685, 689, 641, 591,
    # 2002
    691, 525, 647, 733, 616, 662, 608, 577, 584, 664, 755, 631,
    # 2003
    545, 734, 627, 584, 613, 595, 690, 691, 741, 706, 777, 717,
    # 2004
    713, 630, 744, 679, 747, 662, 638, 706, 676, 723, 810, 787,
    # 2005
    692, 881, 793, 739, 714, 695, 803, 697, 855, 764, 677, 930,
    # 2006
    791, 766, 794, 702, 721, 752, 733, 701, 788, 891, 981, 795,
    # 2007
    656, 614, 872, 798, 784, 754, 866, 851, 923, 912, 840, 802,
    # 2008
    780, 955, 1025, 879, 842, 858, 885, 832, 888, 924, 946, 909,
    # 2009
    676, 812, 892, 772, 829, 882, 874, 898, 903, 908, 915, 844,
    # 2010
    747, 856, 975, 889, 935, 926, 996, 982, 995, 1014, 978, 939,
    # 2011
    830, 957, 1040, 984, 1037, 1098, 1087, 1080, 1113, 1041, 1027, 1078,
    # 2012
    864, 1078, 1234, 1099, 1236, 1212, 1201, 1177, 1250, 1258, 1043, 1107,
    # 2013
    919, 1189, 1109, 1176, 1155, 1234, 1227, 1207, 1216, 1266, 1169, 1068,
    # 2014
    1073, 1125, 1218, 1219, 1298, 1288, 1223, 1335, 1326, 1255, 1202, 1284,
    # 2015
    1033, 1318, 1358, 1361, 1310, 1343, 1256, 1288, 1292, 1291, 1213, 1225,
    # 2016
    1143, 1223, 1330, 1276, 1326, 1448, 1290, 1336, 1242, 1259, 1256, 1383,
    # 2017
    1152, 1210, 1372, 1303, 1369, 1351, 1336, 1375, 1277, 1450, 1313, 1246,
    # 2018
    1167, 1283, 1384, 1262, 1374, 1398, 1406, 1386, 1371, 1347, 1426, 1297,
    # 2019
    1179, 1470, 1409, 1353, 1400, 1400, 1355, 1387, 1338, 1324, 1264, 1273,
    # 2020
    1053, 1166, 1279, 1076, 1164, 1252, 1208, 1129, 1213, 1102, 1171, 1180,
    # 2021
    1064, 1244, 1345, 1217, 1230, 1246, 1189, 1193, 1247, 1244, 1168, 1181,
    # 2022
    1064, 1183, 1193, 1076, 1179, 1228, 1228, 1139, 1149, 1216, 1153, 1217,
    # 2023
    1025, 1254, 1267, 1164, 1187, 1244, 1202, 1201, 1255, 1161, 1174, 1196,
    # 2024
    1008, 1220, 1235, 1113, 1174, 1175, 1121, 1109, 1080, 1092, 1109, 1203,
    # 2025
    1052
]

data["Price_Hong_Kong"] = [
    # 1999
    145982, 111466, 107098, 110840, 171299, 120609, 134810, 197841, 124105, 101764, 116814, 121717,
    # 2000
    105856, 145322, 115265, 246998, 146783, 84730, 90154, 142814, 120979, 113442, 80357, 123252,
    # 2001
    88847, 108558, 100328, 111348, 86007, 118730, 154568, 139634, 88864, 86818, 103725, 123769,
    # 2002
    109905, 109661, 93931, 129094, 161389, 104094, 118727, 130344, 104190, 150569, 103804, 145111,
    # 2003
    89051, 114235, 135249, 163281, 112147, 127865, 65409, 123473, 97463, 134399, 95884, 160603,
    # 2004
    187412, 209776, 184265, 128784, 145532, 102939, 115308, 172520, 177500, 195481, 218904, 154476,
    # 2005
    202172, 174658, 188737, 186139, 154018, 263382, 156906, 190947, 158234, 187335, 158178, 125400,
    # 2006
    164435, 109934, 177508, 209266, 164662, 157330, 148642, 182302, 142737, 159353, 173132, 133859,
    # 2007
    170515, 152500, 255132, 174972, 247336, 265347, 216170, 216098, 239545, 251894, 285998, 320998,
    # 2008
    245805, 272987, 252064, 182686, 224380, 257220, 207380, 289009, 235065, 227385, 130122, 123118,
    # 2009
    211261, 217058, 200728, 156567, 410667, 314353, 301793, 220790, 317224, 380750, 274385, 294867,
    # 2010
    283893, 374744, 284753, 226829, 242536, 310642, 234583, 408475, 274434, 284780, 412646, 274154,
    # 2011
    331526, 537609, 384216, 392990, 321200, 434639, 399478, 446679, 471671, 478248, 369572, 568509,
    # 2012
    309228, 664266, 639735, 418258, 459250, 517191, 485276, 426612, 504662, 522450, 507749, 433457,
    # 2013
    547133, 505915, 611711, 522757, 422778, 330516, 665084, 429936, 526425, 527919, 597525, 356256,
    # 2014
    763571, 507753, 546391, 386764, 387316, 446014, 342918, 388295, 378716, 571173, 435310, 438674,
    # 2015
    642365, 409872, 472611, 555156, 457014, 539458, 817901, 469975, 655026, 437688, 649839, 361025,
    # 2016
    425890, 464599, 888210, 359300, 350826, 513095, 282890, 517052, 478929, 470705, 492334, 389647,
    # 2017
    384780, 529939, 675458, 455688, 430574, 517635, 696957, 418273, 420152, 468486, 701148, 615585,
    # 2018
    430806, 436367, 380580, 656849, 715553, 468131, 382839, 446894, 526729, 578267, 451404, 463241,
    # 2019
    710901, 520952, 548966, 477196, 284772, 498969, 500770, 649855, 348148, 709924, 611661, 333695,
    # 2020
    593236, 426119, 446465, 404816, 512103, 614544, 402504, 405735, 299516, 418228, 469377, 411706,
    # 2021
    486679, 449493, 629964, 433956, 841004, 461994, 534866, 820819, 488126, 721320, 469362, 372590,
    # 2022
    596401, 652607, 445732, 407771, 347841, 384591, 412987, 569386, 358716, 436159, 618109, 565273,
    # 2023
    541724, 512867, 387678, 380100, 846172, 536640, 534154, 420686, 287686, 313675, 569236, 526521,
    # 2024
    506884, 188145, 300955, 325080, 331083, 483706, 470009, 282932, 210695, 280970, 200782, 350286,
    # 2025
    376611
]

data["Price_Kowloon"] = [
    # 1999
    136973, 234150, 161751, 227823, 139793, 162409, 198976, 179330, 167909, 133228, 159350, 139414,
    # 2000
    138900, 153169, 135361, 151200, 110113, 160972, 168016, 189570, 121365, 177560, 159277, 165572,
    # 2001
    181467, 169950, 107213, 162749, 100941, 111748, 131437, 141579, 89312, 85488, 122949, 115238,
    # 2002
    113451, 114342, 129542, 146688, 153789, 130090, 127162, 112581, 136765, 101295, 83365, 94103,
    # 2003
    127796, 105209, 106501, 100390, 96032, 79192, 117564, 118308, 131437, 190074, 134839, 147515,
    # 2004
    200152, 244403, 257271, 169056, 193909, 174195, 144230, 158849, 184596, 190919, 257910, 269936,
    # 2005
    260975, 246007, 237654, 264848, 236799, 253153, 182677, 182236, 213887, 150976, 188474, 191409,
    # 2006
    151377, 161011, 183131, 246129, 178198, 135150, 192349, 289441, 166174, 131356, 161852, 205065,
    # 2007
    171248, 151482, 199466, 212890, 201411, 265958, 213524, 174154, 284189, 232567, 200273, 229188,
    # 2008
    236356, 352251, 231691, 243228, 236966, 244444, 214301, 217039, 197271, 154151, 187420, 277947,
    # 2009
    249647, 231359, 233780, 175162, 283822, 253803, 296837, 245223, 244638, 261410, 229718, 245258,
    # 2010
    256572, 209436, 319197, 271703, 301993, 251814, 285980, 265753, 295936, 298159, 407240, 277961,
    # 2011
    355937, 350048, 334518, 395589, 391103, 327275, 282757, 379350, 228687, 292821, 482468, 538450,
    # 2012
    402247, 304592, 506971, 436596, 454303, 443989, 426777, 429680, 427209, 437840, 517822, 448918,
    # 2013
    396516, 513174, 447625, 385033, 356261, 418145, 593362, 405350, 328878, 387876, 419578, 458732,
    # 2014
    437297, 495480, 441660, 369397, 475167, 329482, 349556, 485307, 387921, 467126, 491165, 413716,
    # 2015
    358230, 399922, 462861, 477722, 376477, 364351, 391872, 540594, 449962, 231156, 445839, 298474,
    # 2016
    463191, 433441, 330014, 413074, 342297, 328254, 340809, 573514, 357502, 378523, 471074, 476088,
    # 2017
    357841, 335551, 299383, 492611, 385693, 354524, 406541, 369818, 429095, 380443, 353150, 341376,
    # 2018
    537371, 404305, 511518, 540651, 392954, 366529, 537171, 360223, 421374, 380800, 294118, 398940,
    # 2019
    394355, 287613, 420898, 414128, 371138, 326930, 346927, 353335, 543072, 278221, 462460, 414008,
    # 2020
    284603, 401857, 339961, 399570, 627627, 344210, 389822, 330234, 417515, 323553, 378324, 378554,
    # 2021
    444359, 576579, 401197, 360144, 397993, 423292, 376536, 422468, 364395, 374214, 405087, 372273,
    # 2022
    406945, 533522, 425738, 378317, 319079, 627952, 402621, 351831, 246168, 209374, 286678, 261113,
    # 2023
    490620, 412190, 412678, 409620, 368203, 406325, 307026, 361393, 336683, 241032, 296290, 229753,
    # 2024
    293845, 366646, 377608, 393219, 306766, 210676, 313692, 325882, 316661, 300865, 220072, 231223,
    # 2025
    251695
]

data["Price_New_Territories"] = [
    # 1999
    140446, 111028, 104394, 82195, 153616, 83562, 74664, 109831, 138843, 125460, 84155, 133369,
    # 2000
    83851, 82742, 87326, 85820, 108177, 84231, 109298, 73192, 122937, 84319, 61105, 73788,
    # 2001
    96915, 67510, 93910, 104339, 95171, 88609, 112637, 120699, 83333, 95713, 85432, 67418,
    # 2002
    141865, 118602, 95584, 113116, 105649, 129913, 90347, 93433, 75671, 85352, 109048, 124745,
    # 2003
    100514, 84105, 95777, 72932, 89792, 112701, 65376, 103536, 96725, 108173, 94528, 111844,
    # 2004
    119304, 113606, 109909, 121709, 102805, 86848, 74037, 112112, 100885, 116487, 143206, 112346,
    # 2005
    134359, 224329, 143519, 139002, 128583, 112777, 102379, 144834, 112694, 173529, 168211, 140567,
    # 2006
    89372, 135400, 109177, 114317, 97042, 108510, 105835, 127771, 100784, 116915, 124479, 127475,
    # 2007
    142536, 90419, 129448, 118452, 157059, 135637, 197152, 157296, 144404, 117333, 155240, 139506,
    # 2008
    144421, 168166, 141295, 151578, 112681, 133463, 163842, 175266, 125696, 108912, 137315, 118322,
    # 2009
    117986, 111043, 118444, 138565, 136039, 165520, 150624, 166445, 148861, 153675, 161215, 178292,
    # 2010
    158098, 187398, 195321, 215611, 183090, 194599, 201656, 167272, 199173, 188816, 209075, 239666,
    # 2011
    211455, 202751, 248219, 283995, 243341, 312188, 272101, 250713, 205221, 188060, 331077, 288347,
    # 2012
    160881, 211852, 288188, 311375, 282592, 291524, 292837, 289681, 349717, 321290, 357318, 360797,
    # 2013
    387794, 377482, 353635, 204261, 257508, 410698, 348074, 322626, 423777, 366180, 436247, 292804,
    # 2014
    375731, 446508, 487774, 407947, 369148, 286760, 353402, 362529, 415287, 258531, 359466, 487348,
    # 2015
    439290, 356213, 330603, 328025, 436987, 412280, 319986, 261395, 387031, 318805, 419437, 370612,
    # 2016
    708985, 226707, 347135, 350741, 340558, 400859, 465329, 434829, 255569, 493170, 401414, 392940,
    # 2017
    423087, 298165, 391562, 426177, 417289, 438909, 354989, 319983, 504227, 275079, 460931, 387937,
    # 2018
    323440, 466843, 486844, 348460, 346066, 397519, 408229, 603420, 356483, 316057, 362343, 357436,
    # 2019
    436568, 268503, 389167, 339777, 351026, 288779, 500095, 652198, 394418, 395364, 356524, 339384,
    # 2020
    245277, 306259, 377091, 444133, 405860, 436605, 296271, 310403, 374617, 394771, 486232, 418780,
    # 2021
    345336, 443217, 445447, 461145, 392366, 369550, 433129, 435911, 423847, 402319, 463943, 352431,
    # 2022
    382744, 367038, 329184, 310052, 550326, 323499, 516722, 298763, 418510, 199331, 210584, 463529,
    # 2023
    500042, 263102, 377219, 393806, 480920, 299937, 275554, 252223, 229418, 442932, 244473, 366464,
    # 2024
    453660, 300417, 366779, 229875, 327032, 341507, 212334, 305811, 303584, 268939, 322207, 213410,
    # 2025
    314914
]

# 创建 DataFrame
df = pd.DataFrame(data)

# 保存为 CSV 文件
df.to_csv("private_retail_rents_prices_1999_2025.csv", index=False, encoding='utf-8')
print("已生成 CSV 文件：private_retail_rents_prices_1999_2025.csv")

已生成 CSV 文件：private_retail_rents_prices_1999_2025.csv

In [3]:
import pandas as pd

# 创建数据
data = {
    "Year": [],
    "Month": [],
    "A": [],
    "B": [],
    "C": [],
    "D": [],
    "E": []
}

# 填充数据（从 1999 年 1 月到 2025 年 1 月）
for year in range(1999, 2026):
    months = 12 if year < 2025 else 1  # 2025 年只到 1 月
    for month in range(1, months + 1):
        data["Year"].append(year)
        data["Month"].append(month)

# 从表格中提取数据
# 由于数据量较大，这里手动输入所有数据
data["A"] = [
    # 1999
    5.2, 5.2, 5.2, 5.1, 5.1, 5.1, 5.2, 5.3, 5.4, 5.3, 5.4, 5.4,
    # 2000
    5.3, 5.3, 5.5, 5.6, 5.9, 6.0, 6.0, 5.9, 5.8, 5.9, 6.3, 6.3,
    # 2001
    6.4, 6.5, 6.3, 6.1, 6.3, 6.2, 6.1, 6.3, 6.3, 6.5, 6.5, 6.3,
    # 2002
    6.2, 6.0, 6.1, 6.1, 6.1, 6.1, 6.0, 6.2, 6.5, 6.3, 6.4, 6.3,
    # 2003
    6.4, 6.4, 6.4, 6.3, 6.4, 6.5, 6.5, 6.5, 6.1, 5.9, 5.9, 5.8,
    # 2004
    5.6, 5.4, 5.2, 5.2, 5.2, 5.5, 5.5, 5.3, 5.2, 5.0, 5.2, 5.1,
    # 2005
    5.1, 4.9, 4.6, 4.7, 4.9, 5.0, 5.0, 5.0, 5.1, 5.2, 5.5, 5.3,
    # 2006
    5.2, 5.2, 5.2, 5.2, 5.1, 5.3, 5.3, 5.3, 5.3, 5.4, 5.5, 5.4,
    # 2007
    5.3, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.2, 5.1, 4.9, 4.8,
    # 2008
    4.7, 4.7, 4.7, 4.8, 4.9, 4.8, 4.9, 5.0, 4.9, 5.1, 5.1, 4.8,
    # 2009
    4.7, 4.6, 4.5, 4.3, 4.3, 4.2, 4.1, 4.0, 4.1, 4.1, 4.2, 4.1,
    # 2010
    4.0, 4.0, 4.0, 4.0, 4.1, 4.1, 4.0, 4.0, 4.0, 4.0, 3.9, 3.9,
    # 2011
    3.7, 3.6, 3.6, 3.6, 3.6, 3.6, 3.8, 3.8, 3.8, 3.8, 3.8, 3.8,
    # 2012
    3.8, 3.7, 3.6, 3.5, 3.5, 3.6, 3.6, 3.5, 3.4, 3.4, 3.4, 3.3,
    # 2013
    3.2, 3.2, 3.2, 3.2, 3.2, 3.1, 3.1, 3.1, 3.2, 3.2, 3.2, 3.2,
    # 2014
    3.2, 3.2, 3.2, 3.2, 3.2, 3.1, 3.1, 3.1, 3.0, 3.0, 3.0, 3.0,
    # 2015
    2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 3.0,
    # 2016
    3.0, 3.0, 3.0, 3.0, 3.0, 3.1, 3.0, 3.0, 2.9, 2.9, 2.8, 2.9,
    # 2017
    2.9, 2.9, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.7,
    # 2018
    2.7, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.7, 2.8, 2.8,
    # 2019
    2.8, 2.7, 2.6, 2.5, 2.5, 2.6, 2.6, 2.7, 2.7, 2.6, 2.5, 2.6,
    # 2020
    2.5, 2.5, 2.5, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4,
    # 2021
    2.3, 2.3, 2.3, 2.3, 2.3, 2.4, 2.3, 2.4, 2.4, 2.4, 2.4, 2.4,
    # 2022
    2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.5, 2.6, 2.6, 2.7, 2.8, 2.8,
    # 2023
    2.7, 2.7, 2.7, 2.7, 2.7, 2.8, 2.9, 3.0, 3.1, 3.1, 3.2, 3.2,
    # 2024
    3.3, 3.3, 3.3, 3.3, 3.4, 3.5, 3.6, 3.7, 3.7, 3.6, 3.6, 3.6,
    # 2025
    3.6
]

data["B"] = [
    # 1999
    4.3, 4.3, 4.3, 4.4, 4.3, 4.3, 4.4, 4.4, 4.6, 4.6, 4.6, 4.5,
    # 2000
    4.4, 4.4, 4.5, 4.7, 4.9, 5.1, 5.0, 4.9, 5.0, 5.1, 5.2, 5.3,
    # 2001
    5.4, 5.4, 5.2, 5.2, 5.2, 5.2, 5.2, 5.3, 5.3, 5.5, 5.3, 5.2,
    # 2002
    5.1, 5.1, 5.1, 5.1, 5.0, 5.0, 5.0, 5.2, 5.2, 5.3, 5.2, 5.2,
    # 2003
    5.2, 5.2, 5.4, 5.4, 5.3, 5.3, 5.4, 5.4, 5.1, 5.0, 4.9, 4.9,
    # 2004
    4.7, 4.4, 4.2, 4.2, 4.4, 4.5, 4.5, 4.4, 4.2, 4.1, 4.2, 4.2,
    # 2005
    4.2, 4.0, 3.8, 3.9, 3.9, 4.0, 4.1, 4.0, 4.1, 4.3, 4.4, 4.3,
    # 2006
    4.2, 4.2, 4.2, 4.2, 4.1, 4.2, 4.2, 4.2, 4.3, 4.3, 4.3, 4.3,
    # 2007
    4.3, 4.2, 4.3, 4.3, 4.2, 4.2, 4.2, 4.3, 4.3, 4.2, 4.2, 4.1,
    # 2008
    4.0, 4.0, 4.1, 4.1, 4.1, 4.2, 4.2, 4.2, 4.1, 4.3, 4.3, 3.9,
    # 2009
    3.7, 3.7, 3.6, 3.5, 3.5, 3.5, 3.4, 3.5, 3.6, 3.6, 3.6, 3.6,
    # 2010
    3.5, 3.4, 3.5, 3.5, 3.6, 3.6, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5,
    # 2011
    3.3, 3.2, 3.2, 3.2, 3.2, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3,
    # 2012
    3.3, 3.2, 3.1, 3.1, 3.1, 3.1, 3.2, 3.2, 3.1, 3.1, 3.1, 3.0,
    # 2013
    2.9, 2.9, 2.8, 2.9, 2.9, 2.8, 2.8, 2.8, 2.9, 2.9, 2.9, 2.9,
    # 2014
    2.9, 2.9, 2.9, 2.9, 2.9, 2.8, 2.8, 2.8, 2.8, 2.8, 2.7, 2.7,
    # 2015
    2.7, 2.6, 2.6, 2.6, 2.7, 2.7, 2.6, 2.7, 2.7, 2.7, 2.7, 2.7,
    # 2016
    2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.6, 2.6, 2.6, 2.6,
    # 2017
    2.6, 2.6, 2.6, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5,
    # 2018
    2.4, 2.4, 2.4, 2.4, 2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.5, 2.5,
    # 2019
    2.5, 2.5, 2.4, 2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.3, 2.3,
    # 2020
    2.3, 2.3, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2,
    # 2021
    2.2, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.2, 2.2, 2.2, 2.2, 2.2,
    # 2022
    2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.3, 2.3, 2.4, 2.4, 2.4,
    # 2023
    2.4, 2.3, 2.3, 2.3, 2.4, 2.4, 2.5, 2.6, 2.6, 2.7, 2.7, 2.8,
    # 2024
    2.8, 2.8, 2.8, 2.8, 2.9, 3.0, 3.0, 3.1, 3.2, 3.1, 3.1, 3.1,
    # 2025
    3.1
]

data["C"] = [
    # 1999
    4.3, 4.4, 4.5, 4.4, 4.4, 4.4, 4.5, 4.5, 4.5, 4.6, 4.6, 4.5,
    # 2000
    4.4, 4.5, 4.5, 4.6, 4.9, 4.9, 5.0, 5.0, 5.0, 5.2, 5.3, 5.3,
    # 2001
    5.4, 5.4, 5.3, 5.2, 5.3, 5.1, 5.3, 5.5, 5.5, 5.6, 5.6, 5.4,
    # 2002
    5.4, 5.4, 5.3, 5.2, 5.1, 5.1, 5.2, 5.2, 5.2, 5.1, 5.0, 5.0,
    # 2003
    4.9, 4.9, 5.2, 5.2, 5.0, 5.0, 5.1, 5.1, 4.7, 4.4, 4.5, 4.5,
    # 2004
    4.3, 4.0, 3.8, 3.9, 3.9, 4.2, 4.2, 4.0, 3.9, 3.7, 3.9, 3.9,
    # 2005
    3.8, 3.7, 3.5, 3.6, 3.5, 3.7, 3.7, 3.8, 3.6, 3.9, 4.0, 4.0,
    # 2006
    3.9, 3.9, 3.7, 3.8, 3.7, 3.8, 4.0, 3.8, 3.7, 3.8, 3.7, 3.8,
    # 2007
    3.8, 3.8, 3.9, 3.8, 3.8, 3.9, 3.8, 3.8, 3.9, 3.8, 3.6, 3.5,
    # 2008
    3.5, 3.5, 3.6, 3.7, 3.6, 3.7, 3.8, 3.8, 3.8, 4.1, 4.1, 3.7,
    # 2009
    3.4, 3.4, 3.3, 3.2, 3.0, 3.0, 3.1, 3.0, 3.0, 3.0, 3.1, 3.1,
    # 2010
    3.1, 3.1, 3.0, 3.1, 3.1, 3.1, 3.1, 3.0, 3.1, 3.1, 3.0, 3.0,
    # 2011
    2.9, 2.8, 2.8, 2.9, 2.8, 2.9, 2.9, 3.0, 2.9, 3.0, 3.0, 3.0,
    # 2012
    3.0, 2.9, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8,
    # 2013
    2.7, 2.6, 2.6, 2.6, 2.6, 2.7, 2.6, 2.6, 2.6, 2.6, 2.7, 2.6,
    # 2014
    2.6, 2.6, 2.6, 2.7, 2.7, 2.7, 2.7, 2.7, 2.6, 2.6, 2.6, 2.6,
    # 2015
    2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.7, 2.6,
    # 2016
    2.7, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.5, 2.5, 2.4, 2.5,
    # 2017
    2.5, 2.5, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.3, 2.3,
    # 2018
    2.3, 2.3, 2.3, 2.3, 2.2, 2.2, 2.2, 2.2, 2.3, 2.3, 2.4, 2.4,
    # 2019
    2.4, 2.3, 2.3, 2.2, 2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.2, 2.3,
    # 2020
    2.2, 2.3, 2.2, 2.2, 2.1, 2.1, 2.1, 2.2, 2.1, 2.1, 2.2, 2.1,
    # 2021
    2.1, 2.1, 2.0, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1,
    # 2022
    2.1, 2.1, 2.1, 2.1, 2.0, 2.1, 2.1, 2.2, 2.1, 2.2, 2.3, 2.3,
    # 2023
    2.2, 2.2, 2.1, 2.2, 2.2, 2.3, 2.3, 2.3, 2.4, 2.4, 2.5, 2.5,
    # 2024
    2.6, 2.5, 2.5, 2.5, 2.6, 2.6, 2.7, 2.8, 2.8, 2.8, 2.7, 2.7,
    # 2025
    2.8
]

data["D"] = [
    # 1999
    4.5, 4.7, 4.6, 4.5, 4.5, 4.3, 4.3, 4.4, 4.4, 4.5, 4.6, 4.5,
    # 2000
    4.4, 4.4, 4.4, 4.4, 4.5, 4.9, 4.9, 4.9, 4.9, 4.9, 5.1, 5.1,
    # 2001
    5.1, 5.3, 5.2, 5.2, 5.5, 5.5, 5.4, 5.4, 5.5, 5.5, 5.5, 5.3,
    # 2002
    5.3, 5.3, 5.3, 5.2, 5.1, 5.0, 5.0, 5.0, 5.0, 4.9, 4.8, 4.9,
    # 2003
    4.9, 4.9, 5.1, 5.1, 4.9, 4.8, 4.9, 4.8, 4.4, 4.3, 4.3, 4.0,
    # 2004
    4.1, 3.9, 3.5, 3.6, 3.8, 4.0, 3.9, 4.0, 3.7, 3.6, 3.6, 3.5,
    # 2005
    3.4, 3.6, 3.4, 3.3, 3.3, 3.3, 3.4, 3.4, 3.4, 3.4, 3.6, 3.6,
    # 2006
    3.6, 3.7, 3.6, 3.5, 3.4, 3.6, 3.6, 3.5, 3.5, 3.6, 3.5, 3.6,
    # 2007
    3.7, 3.6, 3.6, 3.6, 3.7, 3.6, 3.6, 3.5, 3.5, 3.5, 3.4, 3.3,
    # 2008
    3.3, 3.4, 3.4, 3.4, 3.4, 3.4, 3.7, 3.6, 3.7, 3.8, 4.0, 3.6,
    # 2009
    3.3, 3.2, 3.1, 2.9, 2.9, 2.8, 2.7, 2.7, 2.7, 2.7, 2.8, 2.7,
    # 2010
    2.7, 2.7, 2.6, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.7,
    # 2011
    2.7, 2.7, 2.7, 2.6, 2.6, 2.6, 2.6, 2.7, 2.7, 2.7, 2.7, 2.7,
    # 2012
    2.7, 2.7, 2.6, 2.6, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5,
    # 2013
    2.5, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4,
    # 2014
    2.4, 2.4, 2.4, 2.5, 2.5, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4,
    # 2015
    2.4, 2.3, 2.4, 2.4, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.4, 2.4,
    # 2016
    2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.3, 2.3, 2.3, 2.3,
    # 2017
    2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.2, 2.2, 2.2,
    # 2018
    2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.2, 2.2, 2.3, 2.2,
    # 2019
    2.2, 2.2, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1,
    # 2020
    2.0, 2.1, 2.1, 2.1, 2.0, 2.0, 2.0, 2.0, 2.0, 2.1, 2.1, 2.0,
    # 2021
    2.1, 2.0, 1.9, 2.0, 2.0, 2.0, 2.0, 2.0, 1.9, 2.0, 2.0, 2.0,
    # 2022
    2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.0, 2.1, 2.1, 2.1, 2.1,
    # 2023
    2.1, 2.1, 2.1, 2.1, 2.2, 2.2, 2.2, 2.2, 2.3, 2.3, 2.4, 2.4,
    # 2024
    2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.5, 2.5, 2.6, 2.5, 2.5, 2.5,
    # 2025
    2.5
]

data["E"] = [
    # 1999
    4.5, 4.4, 4.6, 4.2, 4.1, 4.1, 4.2, 4.1, 4.3, 4.2, 4.0, 4.2,
    # 2000
    3.9, 4.1, 4.1, 4.2, 4.4, 4.5, 4.6, 4.6, 4.5, 4.5, 4.5, 4.6,
    # 2001
    4.7, 4.9, 5.1, 4.9, 5.0, 5.0, 5.0, 4.9, 5.1, 5.4, 5.1, 5.1,
    # 2002
    5.0, 4.8, 4.8, 4.6, 4.6, 4.7, 4.8, 4.9, 5.0, 4.9, 4.7, 4.4,
    # 2003
    4.4, 4.7, 4.7, 4.7, 4.7, 4.6, 4.4, 4.3, 4.3, 4.0, 3.9, 3.8,
    # 2004
    3.5, 3.3, 3.3, 3.3, 3.3, 3.3, 3.4, 3.4, 3.3, 3.1, 3.2, 3.1,
    # 2005
    3.0, 3.0, 2.9, 2.8, 2.9, 3.0, 3.1, 3.1, 3.1, 3.0, 3.2, 3.1,
    # 2006
    3.0, 3.0, 3.0, 3.0, 3.2, 3.0, 3.3, 3.1, 3.1, 3.3, 3.4, 3.3,
    # 2007
    3.1, 3.2, 3.2, 3.1, 3.1, 3.1, 3.3, 3.1, 3.0, 2.9, 2.9, 2.8,
    # 2008
    2.9, 2.9, 2.9, 2.9, 3.0, 3.0, 3.0, 3.0, 3.3, 3.4, 3.7, 3.1,
    # 2009
    3.0, 2.9, 2.8, 2.5, 2.4, 2.5, 2.5, 2.3, 2.3, 2.4, 2.5, 2.4,
    # 2010
    2.4, 2.3, 2.3, 2.5, 2.6, 2.6, 2.4, 2.4, 2.4, 2.5, 2.5, 2.5,
    # 2011
    2.5, 2.4, 2.4, 2.4, 2.3, 2.3, 2.4, 2.5, 2.5, 2.5, 2.5, 2.4,
    # 2012
    2.4, 2.4, 2.3, 2.3, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2,
    # 2013
    2.2, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1,
    # 2014
    2.2, 2.1, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2,
    # 2015
    2.2, 2.1, 2.1, 2.2, 2.2, 2.2, 2.2, 2.2, 2.1, 2.2, 2.2, 2.3,
    # 2016
    2.3, 2.3, 2.3, 2.2, 2.2, 2.2, 2.2, 2.2, 2.1, 2.1, 2.1, 2.0,
    # 2017
    2.0, 2.0, 2.0, 2.1, 2.1, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0,
    # 2018
    1.9, 1.9, 1.9, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.1, 2.1, 2.1,
    # 2019
    2.1, 2.1, 2.1, 2.1, 2.0, 2.0, 2.1, 2.2, 2.2, 2.2, 2.1, 2.1,
    # 2020
    2.1, 2.0, 2.0, 2.0, 1.9, 1.9, 1.9, 1.9, 1.9, 2.0, 2.0, 1.9,
    # 2021
    1.9, 1.8, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9, 2.0, 2.0, 2.1, 2.1,
    # 2022
    2.0, 2.1, 2.1, 2.1, 2.0, 2.0, 2.0, 2.0, 2.0, 2.1, 2.1, 2.0,
    # 2023
    2.0, 1.9, 1.9, 1.9, 2.0, 2.1, 2.1, 2.1, 2.1, 2.2, 2.2, 2.2,
    # 2024
    2.3, 2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.4, 2.4,
    # 2025
    2.4
]

# 创建 DataFrame
df = pd.DataFrame(data)

# 保存为 CSV 文件
df.to_csv("property_market_yields_1999_2025.csv", index=False, encoding='utf-8')
print("已生成 CSV 文件：property_market_yields_1999_2025.csv")

已生成 CSV 文件：property_market_yields_1999_2025.csv

In [4]:
import pandas as pd

# 创建数据
data = {
    "Year": [],
    "Month": [],
    "Primary_Sales_No": [],
    "Primary_Sales_Consideration": [],
    "Secondary_Sales_No": [],
    "Secondary_Sales_Consideration": []
}

# 填充数据（从 2002 年 1 月到 2025 年 1 月）
for year in range(2002, 2026):
    months = 12 if year < 2025 else 1  # 2025 年只到 1 月
    for month in range(1, months + 1):
        data["Year"].append(year)
        data["Month"].append(month)

# 从表格中提取数据
# 由于数据量较大，这里手动输入所有数据
data["Primary_Sales_No"] = [
    # 2002
    2718, 1506, 1709, 2543, 2257, 2087, 755, 796, 3278, 2282, 1340, 1817,
    # 2003
    2291, 966, 1655, 2431, 1257, 1602, 2765, 2766, 1867, 3958, 2602, 2338,
    # 2004
    2894, 3734, 3705, 1379, 961, 2100, 2421, 1099, 1558, 1801, 2576, 1466,
    # 2005
    1056, 2092, 993, 918, 2471, 2028, 1150, 569, 524, 2762, 1228, 203,
    # 2006
    148, 251, 895, 781, 1137, 1105, 552, 1421, 3929, 1165, 953, 1649,
    # 2007
    994, 1267, 834, 2410, 2293, 1173, 1402, 1886, 2434, 1901, 2573, 956,
    # 2008
    1702, 690, 2399, 540, 638, 2058, 457, 216, 917, 403, 131, 895,
    # 2009
    507, 232, 863, 1587, 2525, 2717, 1307, 2301, 1532, 627, 753, 1210,
    # 2010
    975, 564, 2028, 1975, 685, 1318, 1137, 1531, 556, 1656, 747, 474,
    # 2011
    296, 486, 1123, 741, 2054, 1050, 608, 884, 231, 822, 1189, 1396,
    # 2012
    879, 581, 1435, 804, 1092, 827, 1670, 1397, 644, 2264, 1066, 309,
    # 2013
    632, 1197, 1095, 1045, 1328, 135, 211, 546, 871, 773, 1151, 2062,
    # 2014
    1760, 1142, 693, 1136, 841, 1375, 2507, 1606, 1182, 1723, 1119, 1773,
    # 2015
    1465, 1540, 738, 1634, 1808, 1547, 1122, 764, 1602, 1404, 1049, 2153,
    # 2016
    450, 234, 641, 1294, 1476, 1538, 1142, 1628, 3474, 2251, 2212, 453,
    # 2017
    664, 1474, 1435, 2650, 1275, 2320, 952, 1236, 2389, 1541, 1416, 1293,
    # 2018
    828, 1168, 738, 2122, 756, 2070, 1753, 1490, 1252, 2337, 720, 399,
    # 2019
    2191, 1654, 1468, 2789, 3246, 1191, 1810, 1252, 1338, 1387, 2112, 670,
    # 2020
    626, 1016, 619, 775, 1179, 2195, 1673, 1068, 808, 1046, 2201, 2111,
    # 2021
    586, 1553, 1553, 1067, 1572, 1954, 2052, 708, 1926, 1297, 1868, 1514,
    # 2022
    1081, 481, 161, 258, 1492, 1382, 1177, 1564, 1435, 672, 365, 247,
    # 2023
    363, 655, 1787, 1550, 1000, 1019, 810, 742, 964, 356, 547, 959,
    # 2024
    1003, 367, 1499, 3636, 1934, 980, 826, 1154, 521, 1611, 2494, 887,
    # 2025
    768
]

data["Primary_Sales_Consideration"] = [
    # 2002
    8218, 4305, 4190, 6516, 5844, 4840, 1866, 2313, 7005, 5032, 3202, 5757,
    # 2003
    5342, 2001, 6418, 5710, 3314, 3975, 6415, 5755, 5012, 13907, 7897, 7302,
    # 2004
    8698, 12848, 14089, 6884, 4476, 6199, 6587, 4941, 6544, 7923, 11607, 6967,
    # 2005
    6021, 8060, 5049, 5404, 19273, 8073, 7995, 5619, 2515, 15974, 8178, 1047,
    # 2006
    545, 604, 3440, 4334, 5848, 4238, 2063, 6054, 13686, 4455, 4061, 8397,
    # 2007
    4659, 4820, 4501, 20854, 13487, 6745, 7493, 8677, 7163, 14913, 21092, 8066,
    # 2008
    8927, 3614, 11644, 2702, 3788, 23532, 5300, 1208, 3575, 5135, 907, 6999,
    # 2009
    4134, 1653, 8845, 8034, 11478, 14925, 8574, 12865, 20575, 7593, 10592, 9954,
    # 2010
    5433, 4143, 14432, 19177, 6042, 5627, 12103, 21768, 5980, 15427, 13974, 5597,
    # 2011
    3597, 5391, 12647, 9778, 17200, 14850, 10980, 13007, 3586, 6237, 19900, 13712,
    # 2012
    9707, 6132, 17546, 9985, 12894, 9129, 12177, 9889, 8505, 21419, 10780, 2805,
    # 2013
    4895, 12106, 7981, 6805, 10341, 1074, 1872, 4704, 4749, 4955, 16483, 19907,
    # 2014
    14007, 9983, 8051, 11005, 8544, 11078, 29291, 16207, 14776, 23258, 13459, 16498,
    # 2015
    13003, 13527, 8483, 16833, 17805, 14415, 15720, 9016, 14094, 10601, 9026, 18505,
    # 2016
    6188, 3077, 7496, 15975, 20981, 13556, 11828, 14873, 28211, 24198, 31158, 9048,
    # 2017
    8164, 17465, 20632, 38342, 21342, 27416, 12133, 14369, 23434, 15809, 20623, 20783,
    # 2018
    13976, 17159, 11253, 26644, 13200, 29636, 28775, 18236, 17926, 21382, 9776, 11542,
    # 2019
    28401, 17551, 15211, 27707, 32682, 15405, 17937, 12894, 11873, 16951, 19775, 11216,
    # 2020
    7468, 9868, 7555, 8161, 15015, 21462, 22184, 11955, 9601, 9961, 23413, 23131,
    # 2021
    7269, 17229, 20210, 16275, 24951, 28170, 28567, 11305, 21261, 19479, 19014, 17158,
    # 2022
    13699, 6872, 2533, 3417, 18262, 16270, 13451, 12019, 10466, 5230, 4763, 2740,
    # 2023
    5072, 9053, 18872, 25758, 11807, 12718, 7438, 8440, 7663, 4805, 6318, 9684,
    # 2024
    8336, 5677, 13764, 42350, 26255, 12026, 9687, 11253, 5698, 16072, 30838, 11119,
    # 2025
    7692
]

data["Secondary_Sales_No"] = [
    # 2002
    5129, 4189, 3741, 4866, 5068, 5108, 4206, 4085, 3000, 3581, 3601, 3312,
    # 2003
    3896, 2683, 2895, 2942, 2873, 3231, 3760, 3793, 3765, 5402, 5209, 4629,
    # 2004
    4832, 5715, 7744, 7615, 6419, 5262, 4490, 4617, 5827, 7010, 8705, 6700,
    # 2005
    6853, 6168, 7680, 13206, 9992, 8722, 6347, 6729, 6576, 5792, 5080, 4223,
    # 2006
    4751, 5118, 6561, 6068, 6675, 6045, 4846, 5611, 5882, 5170, 6153, 5606,
    # 2007
    6491, 6537, 7205, 7120, 8817, 8480, 7786, 9594, 6319, 9370, 13186, 12547,
    # 2008
    13084, 11891, 7151, 8507, 7643, 8147, 6976, 5068, 5158, 4316, 3133, 3811,
    # 2009
    4368, 4255, 6239, 8269, 9263, 11088, 10716, 8949, 10753, 8673, 8460, 7898,
    # 2010
    9681, 11169, 8832, 10261, 10329, 7812, 11820, 13168, 9868, 7896, 12442, 8854,
    # 2011
    7706, 9904, 9333, 6894, 7627, 7993, 4646, 4555, 4592, 3821, 3606, 2905,
    # 2012
    2628, 3303, 9923, 7413, 7257, 5059, 4039, 6690, 6657, 6450, 5969, 2977,
    # 2013
    4798, 5110, 3439, 2382, 2948, 3605, 3775, 2861, 2815, 2653, 2639, 2605,
    # 2014
    2728, 2017, 2448, 3645, 4429, 4585, 5285, 4606, 4776, 4466, 3729, 4236,
    # 2015
    4947, 4487, 3591, 2915, 3360, 4229, 4271, 3132, 2661, 1896, 1777, 1890,
    # 2016
    1595, 1573, 1728, 3200, 3110, 3082, 3101, 4193, 4352, 4350, 4527, 3097,
    # 2017
    2622, 2605, 4421, 4410, 4457, 3780, 2563, 2778, 3240, 3748, 4278, 4044,
    # 2018
    4442, 4314, 3525, 4524, 4766, 4643, 4338, 3332, 2248, 1906, 1915, 1661,
    # 2019
    2352, 2435, 3763, 5033, 4962, 3436, 2995, 2832, 2109, 2614, 3644, 2514,
    # 2020
    2136, 2556, 3251, 3327, 4805, 4792, 4460, 3290, 4216, 3905, 3869, 3956,
    # 2021
    3976, 4572, 5891, 6258, 5512, 5637, 5527, 4838, 3918, 3346, 3541, 3631,
    # 2022
    3194, 2431, 2708, 3639, 4710, 3444, 2494, 2573, 2440, 2476, 2366, 2260,
    # 2023
    2688, 3627, 4903, 3033, 3003, 2594, 2255, 2505, 1898, 1767, 2007, 1970,
    # 2024
    2474, 2008, 2472, 4915, 3612, 2876, 2897, 2500, 2327, 3086, 3804, 3216,
    # 2025
    2858
]

data["Secondary_Sales_Consideration"] = [
    # 2002
    9966, 8070, 6795, 8739, 11097, 11289, 8406, 7554, 5108, 6626, 5920, 5594,
    # 2003
    6655, 4405, 5102, 4810, 4174, 4994, 6078, 6448, 6235, 13823, 9739, 8068,
    # 2004
    9330, 13463, 18906, 19840, 15388, 11527, 9439, 9201, 12932, 18662, 23368, 16917,
    # 2005
    17269, 15427, 21639, 33258, 26527, 22555, 16342, 16396, 15418, 13933, 11233, 9626,
    # 2006
    11218, 13015, 16406, 15910, 17525, 15194, 11701, 14982, 15282, 13697, 15400, 13973,
    # 2007
    16691, 17312, 20690, 18588, 24700, 24935, 21239, 28083, 16938, 28916, 49024, 44445,
    # 2008
    47600, 40151, 25798, 24862, 22516, 26899, 19838, 13766, 15158, 11143, 8100, 10663,
    # 2009
    11990, 11969, 16603, 23546, 27945, 34788, 34992, 28122, 35588, 28741, 27561, 24771,
    # 2010
    30721, 36635, 33926, 34105, 36806, 27369, 40078, 47456, 35204, 29520, 44857, 34306,
    # 2011
    29736, 40217, 39218, 29218, 32248, 38006, 20792, 18788, 19373, 16226, 15866, 11950,
    # 2012
    12480, 12900, 41494, 34692, 34458, 24941, 19596, 29846, 31932, 33426, 31188, 14355,
    # 2013
    23647, 26589, 19059, 11909, 13685, 17625, 19119, 14862, 14219, 13410, 13899, 15047,
    # 2014
    13252, 11096, 12505, 18112, 23318, 22799, 27822, 25828, 27387, 26446, 21362, 27333,
    # 2015
    30207, 27324, 23360, 18066, 22395, 28828, 28831, 22049, 19426, 11919, 11771, 11317,
    # 2016
    9611, 8692, 9610, 18519, 19935, 19047, 17905, 25764, 27746, 30306, 30502, 23815,
    # 2017
    19275, 18995, 29743, 31240, 32218, 31723, 21079, 19282, 21838, 26079, 33194, 31172,
    # 2018
    35830, 33735, 27557, 35180, 38984, 38387, 36462, 28529, 19157, 17189, 16244, 12534,
    # 2019
    16523, 18529, 30659, 42394, 45764, 29925, 26132, 23689, 15788, 23737, 28004, 20046,
    # 2020
    17310, 20539, 24204, 25572, 37730, 43333, 37310, 28252, 33805, 40092, 34697, 35615,
    # 2021
    32474, 39705, 49138, 55275, 51879, 52703, 50037, 43192, 34794, 30201, 32269, 31350,
    # 2022
    29722, 22601, 24393, 31741, 39767, 28888, 20438, 20473, 18629, 21949, 21098, 18300,
    # 2023
    20359, 27602, 39021, 26610, 24961, 20903, 19153, 20205, 15124, 19693, 13352, 14640,
    # 2024
    19456, 13419, 16298, 35106, 27120, 22465, 25988, 17218, 15140, 21203, 26423, 21444,
    # 2025
    19052
]

# 创建 DataFrame
df = pd.DataFrame(data)

# 保存为 CSV 文件
df.to_csv("domestic_sales_2002_2025.csv", index=False, encoding='utf-8')
print("已生成 CSV 文件：domestic_sales_2002_2025.csv")

已生成 CSV 文件：domestic_sales_2002_2025.csv

In [5]:
import pandas as pd
import re

# 数据提取和整理
data = []

# 原始数据（从1997年至2024年）
lines = [
    "1997\t161.4\t162.7\t168.8\t168.5\t172.9",
    "1998\t118.5\t116.0\t117.3\t116.1\t114.0",
    "1999\t100.0\t100.0\t100.0\t100.0\t100.0",
    "2000\t88.3\t89.5\t91.2\t94.2\t98.7",
    "2001\t77.2\t78.8\t80.8\t83.2\t87.8",
    "2002\t68.1\t70.2\t71.9\t76.6\t81.8",
    "2003\t59.7\t61.1\t65.3\t70.2\t76.2",
    "2004\t72.7\t77.2\t87.8\t96.5\t106.6",
    "2005\t84.9\t91.3\t106.6\t119.1\t131.3",
    "2006\t86.6\t91.6\t108.0\t121.0\t137.6",
    "2007\t98.5\t100.5\t119.6\t138.0\t161.5",
    "2008\t117.6\t116.1\t138.5\t157.2\t183.6",
    "2009\t120.3\t117.2\t135.1\t153.4\t177.1",
    "2010\t152.5\t144.4\t166.2\t187.5\t215.0",
    "2011\t187.3\t173.8\t193.8\t213.3\t241.7",
    "2012\t217.6\t195.7\t208.4\t226.0\t260.9",
    "2013\t260.3\t230.1\t233.5\t244.9\t267.4",
    "2014\t278.7\t243.2\t238.2\t247.8\t264.7",
    "2015\t326.7\t282.8\t265.4\t269.4\t283.4",
    "2016\t314.8\t272.9\t258.8\t264.5\t275.1",
    "2017\t368.3\t318.4\t296.9\t293.1\t306.1",
    "2018\t416.6\t359.3\t333.0\t320.1\t325.2",
    "2019\t425.6\t363.6\t336.6\t329.5\t310.0",
    "2020\t423.2\t364.3\t328.2\t317.3\t309.5",
    "2021\t436.2\t378.2\t344.0\t331.5\t319.2",
    "2022\t407.5\t357.4\t329.8\t314.6\t301.4",
    "2023\t366.7\t327.8\t310.0\t299.3\t297.6",
    "2024\t318.8\t291.4\t282.3\t274.0\t270.2"
]

for line in lines:
    # 移除行首行尾的空白字符和多余的制表符
    line = line.strip()
    # 分割每行数据
    parts = line.split('\t')
    # 移除空字段（可能由多余的制表符导致）
    parts = [part for part in parts if part]
    
    # 提取年份
    year = parts[0].strip()
    
    # 提取指数数据
    indices = parts[1:]
    
    # 确保指数数据长度正确（A, B, C, D, E = 5个值）
    if len(indices) != 5:
        print(f"Warning: Incorrect number of index values in {year}: {len(indices)} values found.")
        continue
    
    # 清理指数数据：转换为浮点数
    cleaned_indices = []
    for index in indices:
        index = index.strip()
        try:
            index = float(index)
        except ValueError:
            index = None
        cleaned_indices.append(index)
    
    # 构造一行数据
    row = {
        'Year': int(year),
        'A': cleaned_indices[0],
        'B': cleaned_indices[1],
        'C': cleaned_indices[2],
        'D': cleaned_indices[3],
        'E': cleaned_indices[4]
    }
    data.append(row)

# 创建 DataFrame
df = pd.DataFrame(data)

# 保存为 CSV 文件
df.to_csv('private_domestic_price_indices_1997_2024.csv', index=False)
print("已生成 CSV 文件：private_domestic_price_indices_1997_2024.csv")

# 打印前几行以验证
print("CSV 文件前几行：")
print(df.head())

已生成 CSV 文件：private_domestic_price_indices_1997_2024.csv
CSV 文件前几行：
   Year      A      B      C      D      E
0  1997  161.4  162.7  168.8  168.5  172.9
1  1998  118.5  116.0  117.3  116.1  114.0
2  1999  100.0  100.0  100.0  100.0  100.0
3  2000   88.3   89.5   91.2   94.2   98.7
4  2001   77.2   78.8   80.8   83.2   87.8

In [6]:
# Cell to generate population_hk_sar.csv
import pandas as pd

# Data dictionary for population data
data_population = {
    'Year': [2005, 2010, 2015, 2020, 2022, 2023, 2024, 2025, 2030, 2035, 2040, 2045, 2050],
    'Population': [6908486, 7101617, 7366409, 7490235, 7465915, 7442734, 7414909, 7396076, 7252647, 7051626, 6816568, 6498690, 6090619],
    'Yearly % Change': [0.60, 0.55, 0.73, 0.33, -0.16, -0.31, -0.37, -0.25, -0.39, -0.56, -0.68, -0.95, -1.29],
    'Yearly Change': [40764, 38626, 52958, 24765, -12160, -23181, -27825, -18833, -28686, -40204, -47012, -63576, -81614],
    'Migrants (net)': [-1488, 8307, 10547, -1800, -3427, -3427, -19272, 17863, -6941, -20318, -3843, -1140, -2103],
    'Median Age': [37.7, 39.9, 41.7, 44.4, 45.6, 46.2, 46.8, 47.4, 50.4, 53.5, 56.5, 59.3, 62.0],
    'Fertility Rate': [0.96, 1.12, 1.23, 0.89, 0.71, 0.72, 0.73, 0.73, 0.79, 0.83, 0.88, 0.92, 0.96],
    'Density (P/Km²)': [6580, 6763, 7016, 7134, 7110, 7088, 7062, 7044, 6907, 6716, 6492, 6189, 5801],
    'Urban Pop %': [98.8, 98.9, 98.4, None, None, None, None, None, None, None, None, None, None],
    'Urban Population': [6827761, 7025221, 7245701, 7887001292, 8021407192, 8091734930, 8161972572, 8231613070, 8569124911, 8885210181, 9177190203, 9439639668, 9664378587],
    "Country's Share of World Pop": [0.10, 0.10, 0.099, 0.095, 0.093, 0.092, 0.091, 0.090, 0.085, 0.079, 0.074, 0.069, 0.063],
    'World Population': [6586970132, 7021732148, 7470491872, 7887001292, 8021407192, 8091734930, 8161972572, 8231613070, 8569124911, 8885210181, 9177190203, 9439639668, 9664378587],
    'Global Rank': [99, 102, 102, 103, 104, 104, 105, 106, 110, 111, 115, 117, 119]
}

# Create DataFrame
df_population = pd.DataFrame(data_population)

# Save to CSV
df_population.to_csv('population_hk_sar.csv', index=False, encoding='utf-8')
print("Saved 'population_hk_sar.csv'")

# Verify the data
df_population.head()

Saved 'population_hk_sar.csv'

,Year,Population,Yearly % Change,Yearly Change,Migrants (net),Median Age,Fertility Rate,Density (P/Km²),Urban Pop %,Urban Population,Country's Share of World Pop,World Population,Global Rank
0,2005,6908486,0.60,40764,-1488,37.7,0.96,6580,98.8,6827761,0.100,6586970132,99
1,2010,7101617,0.55,38626,8307,39.9,1.12,6763,98.9,7025221,0.100,7021732148,102
2,2015,7366409,0.73,52958,10547,41.7,1.23,7016,98.4,7245701,0.099,7470491872,102
3,2020,7490235,0.33,24765,-1800,44.4,0.89,7134,NaN,7887001292,0.095,7887001292,103
4,2022,7465915,-0.16,-12160,-3427,45.6,0.71,7110,NaN,8021407192,0.093,8021407192,104

In [7]:
import pandas as pd
from io import StringIO

# Combined CSV data as a string
combined_csv = """Year,GDP Growth Rate (%),Unemployment Rate (%),Annual Change in Unemployment (%),Real Interest Rate (%)
2002,1.65670091974147,7.28,2.19,8.80561310998132
2003,3.05628426052773,7.86,0.58,11.7112780077962
2004,8.70002142729743,6.74,-1.12,8.93239063221918
2005,7.38815597842218,5.58,-1.16,6.36795110082956
2006,7.0326067617255,4.77,-0.81,8.49691160575335
2007,6.4648486340803,4.01,-0.76,4.29047247517022
2008,2.12791614864771,3.56,-0.45,3.98001402775793
2009,-2.45913556857734,5.26,1.70,5.39567446922388
2010,6.76769570235129,4.33,-0.93,4.71660338181728
2011,4.81471108602818,3.42,-0.91,1.06078361145656
2012,1.70028899867609,3.29,-0.14,1.40535671774578
2013,3.10150834740608,3.40,0.12,3.130773330882
2014,2.76242285756518,3.30,-0.10,2.0901603044543
2015,2.38777713430783,3.31,0.02,1.30874321411279
2016,2.17543135634364,3.39,0.08,3.30754228059141
2017,3.7961040663029,3.12,-0.27,2.06007106117858
2018,2.84692770115917,2.81,-0.32,1.33331966702298
2019,-1.67239123872136,2.92,0.11,2.99794472987414
2020,-6.54476757335387,5.81,2.89,4.33404298552532
2021,6.45440824066419,5.17,-0.63,4.28705514626083
2022,-3.68357113148396,4.32,-0.86,3.35858659999335
2023,3.27652625631858,3.93,-0.39,2.91219092527806"""

# Convert string to a file-like object and read it
df = pd.read_csv(StringIO(combined_csv))

# Display the data
print(df)

    Year  GDP Growth Rate (%)  Unemployment Rate (%)  \
0   2002             1.656701                   7.28
1   2003             3.056284                   7.86
2   2004             8.700021                   6.74
3   2005             7.388156                   5.58
4   2006             7.032607                   4.77
5   2007             6.464849                   4.01
6   2008             2.127916                   3.56
7   2009            -2.459136                   5.26
8   2010             6.767696                   4.33
9   2011             4.814711                   3.42
10  2012             1.700289                   3.29
11  2013             3.101508                   3.40
12  2014             2.762423                   3.30
13  2015             2.387777                   3.31
14  2016             2.175431                   3.39
15  2017             3.796104                   3.12
16  2018             2.846928                   2.81
17  2019            -1.672391                   2.92
18  2020            -6.544768                   5.81
19  2021             6.454408                   5.17
20  2022            -3.683571                   4.32
21  2023             3.276526                   3.93

    Annual Change in Unemployment (%)  Real Interest Rate (%)
0                                2.19                8.805613
1                                0.58               11.711278
2                               -1.12                8.932391
3                               -1.16                6.367951
4                               -0.81                8.496912
5                               -0.76                4.290472
6                               -0.45                3.980014
7                                1.70                5.395674
8                               -0.93                4.716603
9                               -0.91                1.060784
10                              -0.14                1.405357
11                               0.12                3.130773
12                              -0.10                2.090160
13                               0.02                1.308743
14                               0.08                3.307542
15                              -0.27                2.060071
16                              -0.32                1.333320
17                               0.11                2.997945
18                               2.89                4.334043
19                              -0.63                4.287055
20                              -0.86                3.358587
21                              -0.39                2.912191

In [8]:
import pandas as pd
import io

# CSV content for rental prices by class and region
csv_data1 = """Year,A_Hong Kong,A_Kowloon,A_New Territories,B_Hong Kong,B_Kowloon,B_New Territories,C_Hong Kong,C_Kowloon,C_New Territories,D_Hong Kong,D_Kowloon,D_New Territories,E_Hong Kong,E_Kowloon,E_New Territories
1999,193,173,133,197,157,116,248,183,140,274,187,177,307,186,175
2000,192,166,130,198,149,117,252,172,144,276,195,184,316,197,174
2001,187,153,120,191,146,112,254,184,141,282,233,177,328,207,186
2002,165,134,105,168,132,101,225,164,122,247,196,156,305,190,169
2003,152,122,93,147,120,88,191,157,103,216,172,133,261,182,146
2004,167,125,99,168,134,95,213,171,114,234,188,151,275,159,165
2005,188,140,106,184,145,101,243,193,122,263,205,161,318,201,176
2006,216,154,113,207,155,107,258,198,124,298,220,171,355,197,189
2007,246,170,127,237,170,118,289,220,144,335,240,195,396,228,225
2008,278,198,146,271,202,139,336,264,170,397,291,238,473,273,261
2009,236,181,137,226,174,126,272,230,142,304,236,182,362,244,209
2010,285,204,166,275,217,152,327,278,174,358,287,223,409,269,233
2011,331,241,184,314,240,168,359,288,190,399,299,242,469,294,253
2012,325,237,193,304,232,175,346,281,190,391,269,249,465,293,287
2013,377,293,240,347,278,205,383,306,225,419,310,244,477,341,256
2014,397,311,253,358,300,218,391,321,227,412,322,250,466,329,247
2015,435,345,272,392,324,238,421,355,249,438,349,256,466,342,256
2016,415,329,266,372,302,226,395,329,233,422,326,247,433,349,235
2017,452,354,296,403,327,251,433,356,259,444,349,256,454,368,240
2018,488,391,314,428,353,267,455,376,270,452,381,269,474,370,252
2019,507,391,316,432,350,266,450,371,271,458,363,268,468,382,244
2020,445,370,299,394,330,254,409,347,256,417,340,254,423,351,230
2021,446,377,307,392,331,260,408,350,263,418,349,259,422,381,241
2022,445,376,307,382,323,255,400,340,257,413,331,253,427,340,227
2023,456,398,313,380,337,257,413,349,256,424,353,249,435,378,224
2024*,480,430,329,396,364,270,426,369,269,436,359,253,445,383,221"""

# CSV content for rental indices by class
csv_data2 = """Year,A,B,C,D,E,A, B & C,D & E,All Classes
1999,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2000,88.3,89.5,91.2,94.2,98.7,89.2,95.4,89.6
2001,77.2,78.8,80.8,83.2,87.8,78.4,84.4,78.7
2002,68.1,70.2,71.9,76.6,81.8,69.5,77.9,69.9
2003,59.7,61.1,65.3,70.2,76.2,61.0,72.0,61.6
2004,72.7,77.2,87.8,96.5,106.6,76.6,99.4,78.0
2005,84.9,91.3,106.6,119.1,131.3,90.4,121.9,92.0
2006,86.6,91.6,108.0,121.0,137.6,91.1,124.9,92.7
2007,98.5,100.5,119.6,138.0,161.5,101.4,143.7,103.5
2008,117.6,116.1,138.5,157.2,183.6,118.6,163.0,120.5
2009,120.3,117.2,135.1,153.4,177.1,119.8,159.0,121.3
2010,152.5,144.4,166.2,187.5,215.0,149.3,193.8,150.9
2011,187.3,173.8,193.8,213.3,241.7,180.8,219.7,182.1
2012,217.6,195.7,208.4,226.0,260.9,205.2,234.5,206.2
2013,260.3,230.1,233.5,244.9,267.4,242.1,249.8,242.4
2014,278.7,243.2,238.2,247.8,264.7,257.1,252.3,256.9
2015,326.7,282.8,265.4,269.4,283.4,297.9,273.2,296.8
2016,314.8,272.9,258.8,264.5,275.1,287.1,267.1,286.1
2017,368.3,318.4,296.9,293.1,306.1,335.8,296.3,333.9
2018,416.6,359.3,333.0,320.1,325.2,380.2,321.5,377.3
2019,425.6,363.6,336.6,329.5,310.0,385.7,324.4,383.0
2020,423.2,364.3,328.2,317.3,309.5,383.6,315.5,381.2
2021,436.2,378.2,344.0,331.5,319.2,395.3,328.6,392.7
2022,407.5,357.4,329.8,314.6,301.4,372.1,311.8,369.7
2023,366.7,327.8,310.0,299.3,297.6,338.8,299.0,337.4
2024*,318.8,291.4,282.3,274.0,270.2,300.0,273.1,298.7"""

# Write the first CSV to a file
with open('hk_rental_prices_by_class_region_1999_2024.csv', 'w') as f:
    f.write(csv_data1)

# Write the second CSV to a file
with open('hk_rental_indices_by_class_1999_2024.csv', 'w') as f:
    f.write(csv_data2)

# Now load the files
df1 = pd.read_csv('hk_rental_prices_by_class_region_1999_2024.csv')
print(df1.head())

df2 = pd.read_csv('hk_rental_indices_by_class_1999_2024.csv')
print(df2.head())

   Year  A_Hong Kong  A_Kowloon  A_New Territories  B_Hong Kong  B_Kowloon  \
0  1999          193        173                133          197        157
1  2000          192        166                130          198        149
2  2001          187        153                120          191        146
3  2002          165        134                105          168        132
4  2003          152        122                 93          147        120

   B_New Territories  C_Hong Kong  C_Kowloon  C_New Territories  D_Hong Kong  \
0                116          248        183                140          274
1                117          252        172                144          276
2                112          254        184                141          282
3                101          225        164                122          247
4                 88          191        157                103          216

   D_Kowloon  D_New Territories  E_Hong Kong  E_Kowloon  E_New Territories
0        187                177          307        186                175
1        195                184          316        197                174
2        233                177          328        207                186
3        196                156          305        190                169
4        172                133          261        182                146
   Year      A      B      C      D      E    A.1   B & C  D & E  All Classes
0  1999  100.0  100.0  100.0  100.0  100.0  100.0   100.0  100.0          NaN
1  2000   88.3   89.5   91.2   94.2   98.7   89.2    95.4   89.6          NaN
2  2001   77.2   78.8   80.8   83.2   87.8   78.4    84.4   78.7          NaN
3  2002   68.1   70.2   71.9   76.6   81.8   69.5    77.9   69.9          NaN
4  2003   59.7   61.1   65.3   70.2   76.2   61.0    72.0   61.6          NaN

In [4]:
import pandas as pd

# 创建数据
data = {
    "Year": [],
    "Month": [],
    "Rent_Hong_Kong": [],
    "Rent_Kowloon": [],
    "Rent_New_Territories": [],
    "Price_Hong_Kong": [],
    "Price_Kowloon": [],
    "Price_New_Territories": []
}

# 填充数据（从 1999 年 1 月到 2025 年 1 月）
for year in range(1999, 2026):
    months = 12 if year < 2025 else 1  # 2025 年只到 1 月
    for month in range(1, months + 1):
        data["Year"].append(year)
        data["Month"].append(month)

# 从表格中提取数据
# 由于数据量较大，这里手动输入所有数据
data["Rent_Hong_Kong"] = [
    # 1999
    776, 793, 790, 759, 717, 847, 831, 704, 821, 686, 835, 729,
    # 2000
    767, 803, 803, 761, 762, 896, 787, 789, 836, 779, 808, 793,
    # 2001
    775, 882, 898, 787, 800, 869, 796, 798, 917, 901, 1066, 796,
    # 2002
    780, 764, 852, 743, 920, 798, 750, 725, 762, 757, 834, 790,
    # 2003
    710, 796, 936, 680, 705, 769, 654, 656, 806, 748, 850, 745,
    # 2004
    703, 893, 821, 689, 944, 933, 907, 820, 862, 833, 900, 844,
    # 2005
    804, 744, 988, 834, 1079, 933, 969, 898, 961, 919, 1126, 941,
    # 2006
    812, 888, 1005, 973, 1034, 951, 1037, 960, 1146, 941, 1151, 1019,
    # 2007
    1000, 887, 1108, 935, 1032, 1146, 1040, 1136, 1132, 1077, 1225, 942,
    # 2008
    1088, 1137, 1274, 1033, 1183, 1153, 1568, 1190, 1224, 1122, 1143, 1050,
    # 2009
    858, 972, 1044, 955, 1068, 1087, 1180, 1150, 1135, 1168, 1212, 1056,
    # 2010
    1015, 985, 1395, 1027, 1266, 1332, 1440, 1262, 1339, 1225, 1187, 1277,
    # 2011
    1039, 1245, 1230, 1192, 1384, 1450, 1311, 1439, 1306, 1280, 1389, 1295,
    # 2012
    1137, 1245, 1555, 1353, 1456, 1489, 1603, 1407, 1733, 1487, 1633, 1450,
    # 2013
    1297, 1288, 1754, 1393, 1639, 1604, 1616, 1546, 1618, 1368, 1759, 1501,
    # 2014
    1232, 1559, 1725, 1648, 1574, 1887, 1699, 1551, 1818, 1546, 1456, 1669,
    # 2015
    1453, 1355, 1560, 1683, 1518, 1796, 1580, 1781, 1579, 1618, 1736, 1514,
    # 2016
    1516, 1464, 1701, 1518, 1474, 1432, 1714, 1402, 1446, 1414, 1453, 1381,
    # 2017
    1463, 1476, 1599, 1620, 1426, 1584, 1472, 1572, 1398, 1470, 1591, 1478,
    # 2018
    1427, 1461, 1551, 1411, 1529, 1574, 1520, 1692, 1682, 1535, 1602, 1383,
    # 2019
    1357, 1504, 1690, 1750, 1531, 1736, 1511, 1537, 1438, 1391, 1421, 1221,
    # 2020
    1182, 1280, 1322, 1144, 1036, 1249, 1173, 1137, 1318, 1149, 1264, 1253,
    # 2021
    1219, 1135, 1340, 1272, 1194, 1358, 1208, 1282, 1339, 1131, 1341, 1270,
    # 2022
    1199, 1278, 1278, 1066, 1219, 1244, 1249, 1212, 1253, 1067, 1265, 1042,
    # 2023
    1031, 1454, 1307, 1296, 1216, 1437, 1257, 1309, 1334, 1174, 1236, 1204,
    # 2024
    1116, 1100, 1141, 1201, 1099, 1169, 1215, 1200, 1303, 1116, 1106, 1066,
    # 2025
    967
]

data["Rent_Kowloon"] = [
    # 1999
    799, 835, 865, 831, 861, 838, 961, 930, 914, 814, 917, 1101,
    # 2000
    813, 1056, 1015, 920, 991, 889, 1066, 950, 909, 955, 1118, 1005,
    # 2001
    889, 1010, 921, 890, 858, 905, 869, 898, 915, 916, 983, 1218,
    # 2002
    772, 829, 950, 853, 890, 815, 889, 789, 765, 872, 928, 1050,
    # 2003
    776, 849, 852, 739, 699, 801, 794, 751, 804, 837, 915, 1216,
    # 2004
    807, 838, 888, 798, 908, 896, 1017, 799, 871, 986, 954, 1053,
    # 2005
    854, 829, 1005, 892, 838, 896, 942, 1138, 946, 993, 996, 1398,
    # 2006
    1138, 914, 1030, 875, 883, 908, 1143, 884, 1057, 1055, 1111, 1065,
    # 2007
    857, 917, 935, 944, 943, 947, 970, 1128, 1094, 1105, 1196, 1316,
    # 2008
    952, 1004, 1169, 998, 1047, 1200, 1180, 1067, 1145, 1096, 1276, 1200,
    # 2009
    965, 930, 1162, 938, 973, 1007, 987, 1097, 1145, 1154, 1321, 1230,
    # 2010
    972, 1001, 1222, 1049, 1097, 1202, 1194, 1137, 1320, 1230, 1341, 1301,
    # 2011
    996, 1036, 1262, 1057, 1236, 1249, 1277, 1343, 1417, 1242, 1465, 1361,
    # 2012
    1235, 1261, 1455, 1296, 1346, 1690, 1389, 1339, 1589, 1524, 1646, 1539,
    # 2013
    1334, 1206, 1547, 1373, 1385, 1416, 1555, 1631, 1695, 1400, 1705, 1343,
    # 2014
    1401, 1360, 1629, 1441, 1430, 1548, 1452, 1463, 1665, 1643, 1827, 1537,
    # 2015
    1497, 1520, 1774, 1518, 1575, 1530, 1498, 1527, 1515, 1367, 1350, 1424,
    # 2016
    1174, 1286, 1448, 1332, 1333, 1289, 1186, 1296, 1547, 1307, 1576, 1233,
    # 2017
    1282, 1330, 1455, 1264, 1450, 1290, 1271, 1382, 1624, 1445, 1561, 1403,
    # 2018
    1328, 1412, 1578, 1481, 1373, 1394, 1301, 1398, 1597, 1499, 1369, 1354,
    # 2019
    1345, 1304, 1591, 1380, 1397, 1362, 1340, 1453, 1448, 1418, 1297, 1318,
    # 2020
    1210, 1169, 1129, 1085, 1176, 1124, 1117, 1069, 1121, 1053, 1160, 1157,
    # 2021
    1033, 1192, 1152, 1096, 1098, 1101, 1030, 1200, 1123, 1103, 1224, 1103,
    # 2022
    1088, 1070, 1115, 1116, 1051, 1126, 1049, 1099, 1110, 1078, 1232, 1114,
    # 2023
    978, 1125, 1187, 1184, 1199, 1170, 1151, 1164, 1208, 1143, 1287, 1210,
    # 2024
    1069, 1104, 1134, 1038, 1023, 1123, 1066, 1045, 1061, 1222, 1438, 1068,
    # 2025
    975
]

data["Rent_New_Territories"] = [
    # 1999
    551, 568, 679, 681, 617, 704, 650, 679, 679, 784, 683, 754,
    # 2000
    622, 619, 771, 679, 739, 787, 697, 760, 807, 768, 883, 789,
    # 2001
    653, 635, 713, 675, 730, 705, 725, 725, 685, 689, 641, 591,
    # 2002
    691, 525, 647, 733, 616, 662, 608, 577, 584, 664, 755, 631,
    # 2003
    545, 734, 627, 584, 613, 595, 690, 691, 741, 706, 777, 717,
    # 2004
    713, 630, 744, 679, 747, 662, 638, 706, 676, 723, 810, 787,
    # 2005
    692, 881, 793, 739, 714, 695, 803, 697, 855, 764, 677, 930,
    # 2006
    791, 766, 794, 702, 721, 752, 733, 701, 788, 891, 981, 795,
    # 2007
    656, 614, 872, 798, 784, 754, 866, 851, 923, 912, 840, 802,
    # 2008
    780, 955, 1025, 879, 842, 858, 885, 832, 888, 924, 946, 909,
    # 2009
    676, 812, 892, 772, 829, 882, 874, 898, 903, 908, 915, 844,
    # 2010
    747, 856, 975, 889, 935, 926, 996, 982, 995, 1014, 978, 939,
    # 2011
    830, 957, 1040, 984, 1037, 1098, 1087, 1080, 1113, 1041, 1027, 1078,
    # 2012
    864, 1078, 1234, 1099, 1236, 1212, 1201, 1177, 1250, 1258, 1043, 1107,
    # 2013
    919, 1189, 1109, 1176, 1155, 1234, 1227, 1207, 1216, 1266, 1169, 1068,
    # 2014
    1073, 1125, 1218, 1219, 1298, 1288, 1223, 1335, 1326, 1255, 1202, 1284,
    # 2015
    1033, 1318, 1358, 1361, 1310, 1343, 1256, 1288, 1292, 1291, 1213, 1225,
    # 2016
    1143, 1223, 1330, 1276, 1326, 1448, 1290, 1336, 1242, 1259, 1256, 1383,
    # 2017
    1152, 1210, 1372, 1303, 1369, 1351, 1336, 1375, 1277, 1450, 1313, 1246,
    # 2018
    1167, 1283, 1384, 1262, 1374, 1398, 1406, 1386, 1371, 1347, 1426, 1297,
    # 2019
    1179, 1470, 1409, 1353, 1400, 1400, 1355, 1387, 1338, 1324, 1264, 1273,
    # 2020
    1053, 1166, 1279, 1076, 1164, 1252, 1208, 1129, 1213, 1102, 1171, 1180,
    # 2021
    1064, 1244, 1345, 1217, 1230, 1246, 1189, 1193, 1247, 1244, 1168, 1181,
    # 2022
    1064, 1183, 1193, 1076, 1179, 1228, 1228, 1139, 1149, 1216, 1153, 1217,
    # 2023
    1025, 1254, 1267, 1164, 1187, 1244, 1202, 1201, 1255, 1161, 1174, 1196,
    # 2024
    1008, 1220, 1235, 1113, 1174, 1175, 1121, 1109, 1080, 1092, 1109, 1203,
    # 2025
    1052
]

data["Price_Hong_Kong"] = [
    # 1999
    145982, 111466, 107098, 110840, 171299, 120609, 134810, 197841, 124105, 101764, 116814, 121717,
    # 2000
    105856, 145322, 115265, 246998, 146783, 84730, 90154, 142814, 120979, 113442, 80357, 123252,
    # 2001
    88847, 108558, 100328, 111348, 86007, 118730, 154568, 139634, 88864, 86818, 103725, 123769,
    # 2002
    109905, 109661, 93931, 129094, 161389, 104094, 118727, 130344, 104190, 150569, 103804, 145111,
    # 2003
    89051, 114235, 135249, 163281, 112147, 127865, 65409, 123473, 97463, 134399, 95884, 160603,
    # 2004
    187412, 209776, 184265, 128784, 145532, 102939, 115308, 172520, 177500, 195481, 218904, 154476,
    # 2005
    202172, 174658, 188737, 186139, 154018, 263382, 156906, 190947, 158234, 187335, 158178, 125400,
    # 2006
    164435, 109934, 177508, 209266, 164662, 157330, 148642, 182302, 142737, 159353, 173132, 133859,
    # 2007
    170515, 152500, 255132, 174972, 247336, 265347, 216170, 216098, 239545, 251894, 285998, 320998,
    # 2008
    245805, 272987, 252064, 182686, 224380, 257220, 207380, 289009, 235065, 227385, 130122, 123118,
    # 2009
    211261, 217058, 200728, 156567, 410667, 314353, 301793, 220790, 317224, 380750, 274385, 294867,
    # 2010
    283893, 374744, 284753, 226829, 242536, 310642, 234583, 408475, 274434, 284780, 412646, 274154,
    # 2011
    331526, 537609, 384216, 392990, 321200, 434639, 399478, 446679, 471671, 478248, 369572, 568509,
    # 2012
    309228, 664266, 639735, 418258, 459250, 517191, 485276, 426612, 504662, 522450, 507749, 433457,
    # 2013
    547133, 505915, 611711, 522757, 422778, 330516, 665084, 429936, 526425, 527919, 597525, 356256,
    # 2014
    763571, 507753, 546391, 386764, 387316, 446014, 342918, 388295, 378716, 571173, 435310, 438674,
    # 2015
    642365, 409872, 472611, 555156, 457014, 539458, 817901, 469975, 655026, 437688, 649839, 361025,
    # 2016
    425890, 464599, 888210, 359300, 350826, 513095, 282890, 517052, 478929, 470705, 492334, 389647,
    # 2017
    384780, 529939, 675458, 455688, 430574, 517635, 696957, 418273, 420152, 468486, 701148, 615585,
    # 2018
    430806, 436367, 380580, 656849, 715553, 468131, 382839, 446894, 526729, 578267, 451404, 463241,
    # 2019
    710901, 520952, 548966, 477196, 284772, 498969, 500770, 649855, 348148, 709924, 611661, 333695,
    # 2020
    593236, 426119, 446465, 404816, 512103, 614544, 402504, 405735, 299516, 418228, 469377, 411706,
    # 2021
    486679, 449493, 629964, 433956, 841004, 461994, 534866, 820819, 488126, 721320, 469362, 372590,
    # 2022
    596401, 652607, 445732, 407771, 347841, 384591, 412987, 569386, 358716, 436159, 618109, 565273,
    # 2023
    541724, 512867, 387678, 380100, 846172, 536640, 534154, 420686, 287686, 313675, 569236, 526521,
    # 2024
    506884, 188145, 300955, 325080, 331083, 483706, 470009, 282932, 210695, 280970, 200782, 350286,
    # 2025
    376611
]

data["Price_Kowloon"] = [
    # 1999
    136973, 234150, 161751, 227823, 139793, 162409, 198976, 179330, 167909, 133228, 159350, 139414,
    # 2000
    138900, 153169, 135361, 151200, 110113, 160972, 168016, 189570, 121365, 177560, 159277, 165572,
    # 2001
    181467, 169950, 107213, 162749, 100941, 111748, 131437, 141579, 89312, 85488, 122949, 115238,
    # 2002
    113451, 114342, 129542, 146688, 153789, 130090, 127162, 112581, 136765, 101295, 83365, 94103,
    # 2003
    127796, 105209, 106501, 100390, 96032, 79192, 117564, 118308, 131437, 190074, 134839, 147515,
    # 2004
    200152, 244403, 257271, 169056, 193909, 174195, 144230, 158849, 184596, 190919, 257910, 269936,
    # 2005
    260975, 246007, 237654, 264848, 236799, 253153, 182677, 182236, 213887, 150976, 188474, 191409,
    # 2006
    151377, 161011, 183131, 246129, 178198, 135150, 192349, 289441, 166174, 131356, 161852, 205065,
    # 2007
    171248, 151482, 199466, 212890, 201411, 265958, 213524, 174154, 284189, 232567, 200273, 229188,
    # 2008
    236356, 352251, 231691, 243228, 236966, 244444, 214301, 217039, 197271, 154151, 187420, 277947,
    # 2009
    249647, 231359, 233780, 175162, 283822, 253803, 296837, 245223, 244638, 261410, 229718, 245258,
    # 2010
    256572, 209436, 319197, 271703, 301993, 251814, 285980, 265753, 295936, 298159, 407240, 277961,
    # 2011
    355937, 350048, 334518, 395589, 391103, 327275, 282757, 379350, 228687, 292821, 482468, 538450,
    # 2012
    402247, 304592, 506971, 436596, 454303, 443989, 426777, 429680, 427209, 437840, 517822, 448918,
    # 2013
    396516, 513174, 447625, 385033, 356261, 418145, 593362, 405350, 328878, 387876, 419578, 458732,
    # 2014
    437297, 495480, 441660, 369397, 475167, 329482, 349556, 485307, 387921, 467126, 491165, 413716,
    # 2015
    358230, 399922, 462861, 477722, 376477, 364351, 391872, 540594, 449962, 231156, 445839, 298474,
    # 2016
    463191, 433441, 330014, 413074, 342297, 328254, 340809, 573514, 357502, 378523, 471074, 476088,
    # 2017
    357841, 335551, 299383, 492611, 385693, 354524, 406541, 369818, 429095, 380443, 353150, 341376,
    # 2018
    537371, 404305, 511518, 540651, 392954, 366529, 537171, 360223, 421374, 380800, 294118, 398940,
    # 2019
    394355, 287613, 420898, 414128, 371138, 326930, 346927, 353335, 543072, 278221, 462460, 414008,
    # 2020
    284603, 401857, 339961, 399570, 627627, 344210, 389822, 330234, 417515, 323553, 378324, 378554,
    # 2021
    444359, 576579, 401197, 360144, 397993, 423292, 376536, 422468, 364395, 374214, 405087, 372273,
    # 2022
    406945, 533522, 425738, 378317, 319079, 627952, 402621, 351831, 246168, 209374, 286678, 261113,
    # 2023
    490620, 412190, 412678, 409620, 368203, 406325, 307026, 361393, 336683, 241032, 296290, 229753,
    # 2024
    293845, 366646, 377608, 393219, 306766, 210676, 313692, 325882, 316661, 300865, 220072, 231223,
    # 2025
    251695
]

data["Price_New_Territories"] = [
    # 1999
    140446, 111028, 104394, 82195, 153616, 83562, 74664, 109831, 138843, 125460, 84155, 133369,
    # 2000
    83851, 82742, 87326, 85820, 108177, 84231, 109298, 73192, 122937, 84319, 61105, 73788,
    # 2001
    96915, 67510, 93910, 104339, 95171, 88609, 112637, 120699, 83333, 95713, 85432, 67418,
    # 2002
    141865, 118602, 95584, 113116, 105649, 129913, 90347, 93433, 75671, 85352, 109048, 124745,
    # 2003
    100514, 84105, 95777, 72932, 89792, 112701, 65376, 103536, 96725, 108173, 94528, 111844,
    # 2004
    119304, 113606, 109909, 121709, 102805, 86848, 74037, 112112, 100885, 116487, 143206, 112346,
    # 2005
    134359, 224329, 143519, 139002, 128583, 112777, 102379, 144834, 112694, 173529, 168211, 140567,
    # 2006
    89372, 135400, 109177, 114317, 97042, 108510, 105835, 127771, 100784, 116915, 124479, 127475,
    # 2007
    142536, 90419, 129448, 118452, 157059, 135637, 197152, 157296, 144404, 117333, 155240, 139506,
    # 2008
    144421, 168166, 141295, 151578, 112681, 133463, 163842, 175266, 125696, 108912, 137315, 118322,
    # 2009
    117986, 111043, 118444, 138565, 136039, 165520, 150624, 166445, 148861, 153675, 161215, 178292,
    # 2010
    158098, 187398, 195321, 215611, 183090, 194599, 201656, 167272, 199173, 188816, 209075, 239666,
    # 2011
    211455, 202751, 248219, 283995, 243341, 312188, 272101, 250713, 205221, 188060, 331077, 288347,
    # 2012
    160881, 211852, 288188, 311375, 282592, 291524, 292837, 289681, 349717, 321290, 357318, 360797,
    # 2013
    387794, 377482, 353635, 204261, 257508, 410698, 348074, 322626, 423777, 366180, 436247, 292804,
    # 2014
    375731, 446508, 487774, 407947, 369148, 286760, 353402, 362529, 415287, 258531, 359466, 487348,
    # 2015
    439290, 356213, 330603, 328025, 436987, 412280, 319986, 261395, 387031, 318805, 419437, 370612,
    # 2016
    708985, 226707, 347135, 350741, 340558, 400859, 465329, 434829, 255569, 493170, 401414, 392940,
    # 2017
    423087, 298165, 391562, 426177, 417289, 438909, 354989, 319983, 504227, 275079, 460931, 387937,
    # 2018
    323440, 466843, 486844, 348460, 346066, 397519, 408229, 603420, 356483, 316057, 362343, 357436,
    # 2019
    436568, 268503, 389167, 339777, 351026, 288779, 500095, 652198, 394418, 395364, 356524, 339384,
    # 2020
    245277, 306259, 377091, 444133, 405860, 436605, 296271, 310403, 374617, 394771, 486232, 418780,
    # 2021
    345336, 443217, 445447, 461145, 392366, 369550, 433129, 435911, 423847, 402319, 463943, 352431,
    # 2022
    382744, 367038, 329184, 310052, 550326, 323499, 516722, 298763, 418510, 199331, 210584, 463529,
    # 2023
    500042, 263102, 377219, 393806, 480920, 299937, 275554, 252223, 229418, 442932, 244473, 366464,
    # 2024
    453660, 300417, 366779, 229875, 327032, 341507, 212334, 305811, 303584, 268939, 322207, 213410,
    # 2025
    314914
]

# 创建 DataFrame
df = pd.DataFrame(data)

# 保存为 CSV 文件
df.to_csv("/Users/mastin/project_folder/private_retail_rents_prices_1999_2025.csv", index=False, encoding='utf-8')
print("已生成 CSV 文件：private_retail_rents_prices_1999_2025.csv")

已生成 CSV 文件：private_retail_rents_prices_1999_2025.csv

In [5]:
import pandas as pd
from io import StringIO

# Combined CSV data as a string
combined_csv = """Year,GDP Growth Rate (%),Unemployment Rate (%),Annual Change in Unemployment (%),Real Interest Rate (%)
2002,1.65670091974147,7.28,2.19,8.80561310998132
2003,3.05628426052773,7.86,0.58,11.7112780077962
2004,8.70002142729743,6.74,-1.12,8.93239063221918
2005,7.38815597842218,5.58,-1.16,6.36795110082956
2006,7.0326067617255,4.77,-0.81,8.49691160575335
2007,6.4648486340803,4.01,-0.76,4.29047247517022
2008,2.12791614864771,3.56,-0.45,3.98001402775793
2009,-2.45913556857734,5.26,1.70,5.39567446922388
2010,6.76769570235129,4.33,-0.93,4.71660338181728
2011,4.81471108602818,3.42,-0.91,1.06078361145656
2012,1.70028899867609,3.29,-0.14,1.40535671774578
2013,3.10150834740608,3.40,0.12,3.130773330882
2014,2.76242285756518,3.30,-0.10,2.0901603044543
2015,2.38777713430783,3.31,0.02,1.30874321411279
2016,2.17543135634364,3.39,0.08,3.30754228059141
2017,3.7961040663029,3.12,-0.27,2.06007106117858
2018,2.84692770115917,2.81,-0.32,1.33331966702298
2019,-1.67239123872136,2.92,0.11,2.99794472987414
2020,-6.54476757335387,5.81,2.89,4.33404298552532
2021,6.45440824066419,5.17,-0.63,4.28705514626083
2022,-3.68357113148396,4.32,-0.86,3.35858659999335
2023,3.27652625631858,3.93,-0.39,2.91219092527806"""

# Convert string to a file-like object and read it
df = pd.read_csv(StringIO(combined_csv))

# 保存为 CSV 文件
df.to_csv('/Users/mastin/project_folder/economic_data.csv', index=False)
print("已生成 CSV 文件：economic_data.csv")

已生成 CSV 文件：economic_data.csv

In [2]:
df.to_csv("/Users/mastin/project_folder/private_retail_rents_prices_1999_2025.csv", index=False, encoding='utf-8')

In [6]:
import pandas as pd
import numpy as np

# 加载所有 CSV 文件（使用绝对路径）
rents_prices = pd.read_csv('/Users/mastin/project_folder/private_retail_rents_prices_1999_2025.csv')
property_yields = pd.read_csv('/Users/mastin/project_folder/property_market_yields_1999_2025.csv')
domestic_sales = pd.read_csv('/Users/mastin/project_folder/domestic_sales_2002_2025.csv')
population = pd.read_csv('/Users/mastin/project_folder/population_hk_sar.csv')
economic = pd.read_csv('/Users/mastin/project_folder/economic_data.csv')
rental_prices = pd.read_csv('/Users/mastin/project_folder/hk_rental_prices_by_class_region_1999_2024.csv')
rental_indices = pd.read_csv('/Users/mastin/project_folder/hk_rental_indices_by_class_1999_2024.csv')

# 表 1：rents_prices
rents_prices = rents_prices.rename(columns={
    'Rent_Hong_Kong': 'Rent_Hong_Kong',
    'Rent_Kowloon': 'Rent_Kowloon',
    'Rent_New_Territories': 'Rent_New_Territories',
    'Price_Hong_Kong': 'Price_Hong_Kong',
    'Price_Kowloon': 'Price_Kowloon',
    'Price_New_Territories': 'Price_New_Territories'
})
rents_prices.to_csv('/Users/mastin/project_folder/db_rents_prices.csv', index=False)

# 表 2：property_yields
property_yields = property_yields.rename(columns={
    'A': 'Yield_A',
    'B': 'Yield_B',
    'C': 'Yield_C',
    'D': 'Yield_D',
    'E': 'Yield_E'
})
property_yields.to_csv('/Users/mastin/project_folder/db_property_yields.csv', index=False)

# 表 3：domestic_sales
domestic_sales = domestic_sales.rename(columns={
    'Primary Sales No.': 'Primary_Sales_No',
    'Primary Sales Consideration ($ million)': 'Primary_Sales_Consideration',
    'Secondary Sales No.': 'Secondary_Sales_No',
    'Secondary Sales Consideration ($ million)': 'Secondary_Sales_Consideration'
})
domestic_sales.to_csv('/Users/mastin/project_folder/db_domestic_sales.csv', index=False)

# 表 4：population
population = population.rename(columns={
    'Yearly % Change': 'Yearly_Percent_Change',
    'Migrants (net)': 'Migrants_Net',
    'Density (P/Km²)': 'Density',
    'Urban Pop %': 'Urban_Pop_Percent',
    "Country's Share of World Pop": 'Share_World_Pop'
})
population.to_csv('/Users/mastin/project_folder/db_population.csv', index=False)

# 表 5：economic_indicators
economic = economic.rename(columns={
    'GDP Growth Rate (%)': 'GDP_Growth_Rate',
    'Unemployment Rate (%)': 'Unemployment_Rate',
    'Annual Change in Unemployment (%)': 'Annual_Change_Unemployment',
    'Real Interest Rate (%)': 'Real_Interest_Rate'
})
economic.to_csv('/Users/mastin/project_folder/db_economic_indicators.csv', index=False)

# 表 6：rental_prices_by_class
rental_prices.to_csv('/Users/mastin/project_folder/db_rental_prices_by_class.csv', index=False)

# 表 7：rental_indices_by_class
rental_indices = rental_indices.rename(columns={
    'A': 'Index_A',
    'B': 'Index_B',
    'C': 'Index_C',
    'D': 'Index_D',
    'E': 'Index_E',
    'A, B & C': 'Index_A_B_C',
    'D & E': 'Index_D_E',
    'All Classes': 'Index_All_Classes'
})
rental_indices.to_csv('/Users/mastin/project_folder/db_rental_indices_by_class.csv', index=False)

print("所有表已整理并保存为 CSV 文件：")
print("1. db_rents_prices.csv")
print("2. db_property_yields.csv")
print("3. db_domestic_sales.csv")
print("4. db_population.csv")
print("5. db_economic_indicators.csv")
print("6. db_rental_prices_by_class.csv")
print("7. db_rental_indices_by_class.csv")

所有表已整理并保存为 CSV 文件：
1. db_rents_prices.csv
2. db_property_yields.csv
3. db_domestic_sales.csv
4. db_population.csv
5. db_economic_indicators.csv
6. db_rental_prices_by_class.csv
7. db_rental_indices_by_class.csv